[workspace]
members = [
    "crates/tachyon",
    "crates/msnp"
]

default-members = [
    "crates/tachyon",
    "crates/msnp"
]

exclude = [
    "lib/matrix-rust-sdk"
]
resolver = "2"

[workspace.dependencies]
anyhow= "1.0.75"
thiserror = "1.0.58"
env_logger = "0.11.3"
lazy_static = "1.4.0"
lazy-static-include = "3.2.1"
regex = "1.10.2"
urlencoding = "2.1.3"
log = "0.4.21"
chrono = "0.4.41"

