[package]
name = "tachyon-backend-matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.92"

anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
log = "0.4.29"

[dependencies.matrix-sdk]
path = "../../lib/matrix-rust-sdk/crates/matrix-sdk"
features = ["e2e-encryption", "automatic-room-key-forwarding", "bundled-sqlite", "native-tls"]


[dev-dependencies.matrix-sdk]
path = "../../lib/matrix-rust-sdk/crates/matrix-sdk"
features = ["testing"]

[dependencies.tachyon-core]
path = "../tachyon-core"

[dev-dependencies]
wiremock = "0.6.5"
